name: Lint

on:
  pull_request:
    branches: [dev, develop, main, master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
